import { averageConfidence, averageEnergy, momentumScore, scoreSignal, stageCounts, strongestSignal, formatRelative } from '../lib/analytics.js';
import { escapeHtml } from '../lib/html.js';
import { signalCard } from './components.js';

export function overviewPage(state) {
  const { signals, activity } = state;
  const counts = stageCounts(signals), momentum = momentumScore(signals, activity), strongest = strongestSignal(signals);
  return `<div class="page-stack">
    <section class="hero-panel"><div><span class="eyebrow">Signal intelligence</span><h1>Не храни идеи.<br><em>Двигай лучшие.</em></h1><p>Signal Garden превращает список задумок в маленькую продуктовую систему: у каждой идеи есть энергия, уверенность, стадия и следующий проверяемый шаг.</p><div class="hero-actions"><a href="/garden" data-link class="button primary">Открыть garden</a><a href="/analytics" data-link class="button secondary">Посмотреть аналитику</a></div></div><div class="signal-radar"><div class="radar-ring ring-a"></div><div class="radar-ring ring-b"></div><div class="radar-ring ring-c"></div><span class="radar-node n1"></span><span class="radar-node n2"></span><span class="radar-node n3"></span><strong>${momentum}</strong><small>momentum</small></div></section>
    <section class="stat-grid"><article><span>Signals</span><strong>${signals.length}</strong><small>${counts.seed} seed · ${counts.growing} growing · ${counts.bloom} bloom</small></article><article><span>Avg. energy</span><strong>${averageEnergy(signals)}%</strong><small>насколько хочется продолжать</small></article><article><span>Confidence</span><strong>${averageConfidence(signals)}%</strong><small>насколько идея подтверждена</small></article><article class="accent-card"><span>7d activity</span><strong>${activity.filter((e)=>Date.now()-e.createdAt<604800000).length}</strong><small>изменений за неделю</small></article></section>
    <section class="overview-grid"><article class="panel focus-panel"><div class="panel-heading"><div><span class="eyebrow">Priority engine</span><h2>Сильнейший сигнал</h2></div><a href="/garden" data-link>Все идеи →</a></div>${strongest ? `<div class="focus-score"><span>${escapeHtml(strongest.category)}</span><strong>${scoreSignal(strongest)}</strong></div><h3>${escapeHtml(strongest.title)}</h3><p>${escapeHtml(strongest.description)}</p><div class="next-step-box"><span>Следующий шаг</span><strong>${escapeHtml(strongest.nextAction)}</strong></div>` : '<p>Создай первый сигнал.</p>'}</article>
    <article class="panel activity-panel"><div class="panel-heading"><div><span class="eyebrow">Activity</span><h2>Последние изменения</h2></div></div><div class="activity-list">${activity.slice(0,6).map((event)=>`<div class="activity-item"><span class="activity-icon type-${event.type}">•</span><div><strong>${escapeHtml(event.signalTitle)}</strong><p>${escapeHtml(event.detail)}</p></div><time>${formatRelative(event.createdAt)}</time></div>`).join('')}</div></article></section>
  </div>`;
}

export function gardenPage(state, ui) {
  const query = ui.query.toLowerCase();
  const filtered = state.signals.filter((signal)=>`${signal.title} ${signal.description} ${signal.tags.join(' ')}`.toLowerCase().includes(query) && (ui.category==='all'||signal.category===ui.category));
  const categories = [...new Set(state.signals.map((s)=>s.category))];
  const stages = [['seed','Seed','Сформулировать проблему'],['growing','Growing','Проверить прототипом'],['bloom','Bloom','Показать результат']];
  return `<div class="page-stack"><section class="page-heading"><div><span class="eyebrow">Kanban workspace</span><h1>Garden</h1><p>Перетаскивай сигналы между стадиями. Фокус — не на количестве карточек, а на движении к следующему доказательству.</p></div></section>
    <section class="toolbar"><label class="search-field"><span>⌕</span><input data-filter="query" value="${escapeHtml(ui.query)}" placeholder="Поиск по идеям и тегам"></label><select data-filter="category"><option value="all">Все категории</option>${categories.map((item)=>`<option ${item===ui.category?'selected':''}>${escapeHtml(item)}</option>`).join('')}</select><span class="result-count">${filtered.length} signals</span></section>
    <section class="kanban">${stages.map(([key,label,hint])=>{ const items=filtered.filter((s)=>s.stage===key); return `<div class="kanban-column" data-drop-stage="${key}"><div class="column-heading"><div><span class="stage-dot stage-${key}">${label}</span><strong>${items.length}</strong></div><small>${hint}</small></div><div class="column-list">${items.map((s)=>signalCard(s,{compact:true,draggable:true})).join('')||'<div class="column-empty">Drop signal here</div>'}</div></div>`;}).join('')}</section></div>`;
}

export function analyticsPage(state) {
  const { signals, activity }=state, counts=stageCounts(signals), momentum=momentumScore(signals,activity), max=Math.max(1,...Object.values(counts));
  const categories=[...new Set(signals.map((s)=>s.category))].map((category)=>{const group=signals.filter((s)=>s.category===category); return {category,count:group.length,energy:Math.round(group.reduce((sum,s)=>sum+s.energy,0)/group.length)}}).sort((a,b)=>b.count-a.count);
  const insight=counts.seed>counts.growing+counts.bloom?'В бэклоге слишком много Seed-сигналов. Не создавай новые идеи: выбери одну и быстро получи внешнее подтверждение.':momentum>=75?'Система в хорошем движении. Следующий сильный ход — довести один Growing-проект до публичного Bloom-результата.':'Momentum умеренный. Выбери идею с высокой энергией и средней уверенностью и проведи один дешёвый тест.';
  return `<div class="page-stack"><section class="page-heading"><div><span class="eyebrow">Decision support</span><h1>Analytics</h1><p>Не vanity metrics: экран отвечает на вопросы «двигаюсь ли я?» и «какие идеи заслуживают следующего часа?».</p></div></section><section class="stat-grid"><article><span>Momentum</span><strong>${momentum}</strong><small>energy + activity + bloom</small></article><article><span>Avg. energy</span><strong>${averageEnergy(signals)}%</strong><small>мотивация продолжать</small></article><article><span>Avg. confidence</span><strong>${averageConfidence(signals)}%</strong><small>сила подтверждений</small></article><article class="accent-card"><span>Events</span><strong>${activity.length}</strong><small>изменений сохранено</small></article></section><section class="analytics-grid"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Pipeline</span><h2>Распределение стадий</h2></div></div><div class="bar-chart">${['seed','growing','bloom'].map((stage)=>`<div class="bar-row"><span>${stage}</span><div><i style="width:${counts[stage]/max*100}%"></i></div><strong>${counts[stage]}</strong></div>`).join('')}</div></article><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Portfolio</span><h2>Категории</h2></div></div><div class="category-table">${categories.map((item)=>`<div><strong>${escapeHtml(item.category)}</strong><span>${item.count} ideas</span><span>${item.energy}% energy</span></div>`).join('')}</div></article></section><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Interpretation</span><h2>Что означает текущая картина</h2></div></div><p class="analysis-copy">${insight}</p></article></div>`;
}

export function settingsPage() {
  return `<div class="page-stack settings-page"><section class="page-heading"><div><span class="eyebrow">Local-first controls</span><h1>Settings</h1><p>Данные живут в браузере, но их можно выгрузить и перенести. Это сознательное архитектурное ограничение frontend-only версии.</p></div></section><section class="settings-grid"><article class="panel"><span class="eyebrow">Portability</span><h2>Экспорт / импорт</h2><p>JSON содержит сигналы и журнал активности. Его можно хранить в Git или использовать для миграции на backend.</p><div class="settings-actions"><button class="button primary" data-action="export">Export JSON</button><button class="button secondary" data-action="import">Import JSON</button><input hidden type="file" accept="application/json" data-import-file></div></article><article class="panel"><span class="eyebrow">Demo state</span><h2>Сбросить данные</h2><p>Вернуть демонстрационный набор карточек и событий. Удобно для возврата к исходному состоянию.</p><button class="button secondary danger-outline" data-action="restore">Restore demo</button></article></section><div data-status></div><article class="panel architecture-panel"><span class="eyebrow">Architecture</span><h2>Как устроено приложение</h2><div class="architecture-list"><div><strong>Domain store</strong><span>CRUD, move и boost инкапсулированы; UI не мутирует данные напрямую.</span></div><div><strong>Event history</strong><span>Каждая значимая операция записывается в activity stream.</span></div><div><strong>Derived analytics</strong><span>Метрики считаются из состояния, а не захардкожены в интерфейсе.</span></div><div><strong>Portable persistence</strong><span>localStorage изолирован; его можно заменить API adapter без переписывания страниц.</span></div></div></article></div>`;
}
